---
title: "Publications"
author: 
  - name: Dr Nipun Shrestha
    url: https://ctc.usyd.edu.au/about-us/our-people/academics-research-fellows/dr-nipun-shrestha/
    email: drnipunsth@gmail.com
    orcid: 0000-0003-3542-8130
    degrees: 
      - MBBS
      - MPH
      - PhD
---

1.            Oja P, Memon AR, Titze S, Jurakic D, Chen ST, Shrestha N, et al. Health Benefits of Different Sports: a Systematic Review and Meta-Analysis of Longitudinal and Intervention Studies Including 2.6 Million Adult Participants. Sports Med Open. 2024;10(1):46. doi: 10.1186/s40798-024-00692-x..

2.            Li M, Yu R, Wang X, Zhao Y, Song Q, Wang Q, et al. Association between ABO genotypes and risk of dementia and neuroimaging markers: roles of sex and APOE status. Frontiers in Neurology. 2024;15. doi: 10.3389/fneur.2024.1391010.

3.            Giebel C, Gabbay M, Shrestha N, Saldarriaga G, Reilly S, White R, et al. Community-based mental health interventions in low- and middle-income countries: a qualitative study with international experts. Int J Equity Health. 2024;23(1):19. doi: 10.1186/s12939-024-02106-6..

4.            Seidler AL, Libesman S, Hunter KE, Barba A, Aberoumand M, Williams JG, et al. Short, medium, and long deferral of umbilical cord clamping compared with umbilical cord milking and immediate clamping at preterm birth: a systematic review and network meta-analysis with individual participant data. Lancet (London, England). 2023;402(10418):2223-34. doi: 10.1016/S0140-6736(23)02469-8.

5.            Seidler AL, Hunter KE, Barba A, Aberoumand M, Libesman S, Williams JG, et al. Optimizing cord management for each preterm baby - Challenges of collating individual participant data and recommendations for future collaborative research. Semin Perinatol. 2023;47(4):151740. doi: 10.1016/j.semperi.2023.151740.

6.            Seidler AL, Aberoumand M, Hunter KE, Barba A, Libesman S, Williams JG, et al. Deferred cord clamping, cord milking, and immediate cord clamping at preterm birth: a systematic review and individual participant data meta-analysis. Lancet (London, England). 2023;402(10418):2209-22. Epub 2023/11/18. doi: 10.1016/s0140-6736(23)02468-6.

7.            Kazmi F, Shrestha N, Foord T, Liu TF, Heesen P, Booth S, et al. Are targeted therapies effective in the relapsed or metastatic cancer setting? A Cochrane meta-analysis. ESMO Open. 2023;8(1). doi: 10.1016/j.esmoop.2023.101649.

8.            Hunter KE, Aberoumand M, Libesman S, Sotiropoulos JX, Williams J, Li W, et al. Development of the Individual Participant Data (IPD) Integrity Tool for assessing the integrity of randomised trials using individual participant data. medRxiv. 2023. doi: 10.1101/2023.12.11.23299797.

9.            Fu C, Hao W, Ma Y, Shrestha N, Virani SS, Mishra SR, et al. Number of Live Births, Age at the Time of Having a Child, Span of Births and Risk of Dementia: A Population-Based Cohort Study of 253,611 U.K. Women. J Womens Health (Larchmt). 2023;32(6):680-92. doi: 10.1089/jwh.2022.0396.

10.         Shrestha N, Parker A, Jurakic D, Biddle SJH, Pedisic Z. Improving Practices of Mental Health Professionals in Recommending More Physical Activity and Less Sedentary Behaviour to Their Clients: An Intervention Trial. Issues Ment Health Nurs. 2022;43(3):258-64. doi: 10.1080/01612840.2021.1972189.

11.         Giebel C, Shrestha N, Reilly S, White RG, Zuluaga MI, Saldarriaga G, et al. Community-based mental health and well-being interventions for older adults in low- and middle-income countries: a systematic review and meta-analysis. BMC Geriatr. 2022;22(1):773. doi: 10.1186/s12877-022-03453-1.

12.         Fu C, Hao W, Shrestha N, Virani SS, Mishra SR, Zhu D. Association of reproductive factors with dementia: A systematic review and dose-response meta-analyses of observational studies. EClinicalMedicine. 2022;43:101236. doi: 10.1016/j.eclinm.2021.101236.

13.         Dong C, Zhou C, Fu C, Hao W, Ozaki A, Shrestha N, et al. Sex differences in the association between cardiovascular diseases and dementia subtypes: a prospective analysis of 464,616 UK Biobank participants. Biol Sex Differ. 2022;13(1):21. doi: 10.1186/s13293-022-00431-5.

14.         Atakan MM, Guzel Y, Shrestha N, Kosar SN, Grgic J, Astorino TA, et al. Effects of high-intensity interval training (HIIT) and sprint interval training (SIT) on fat oxidation during exercise: a systematic review and meta-analysis. Br J Sports Med. 2022. doi: 10.1136/bjsports-2021-105181.

15.         Shrestha N, Pedisic Z, Jurakic D, Biddle SJH, Parker A. Physical activity and sedentary behaviour counselling: Attitudes and practices of mental health professionals. PLoS One. 2021;16(7):e0254684. doi: 10.1371/journal.pone.0254684.

16.         Shrestha N, Mishra SR, Ghimire S, Gyawali B, Marahatta SB, Maskey S, et al. Health System Preparedness for COVID-19 and Its Impacts on Frontline Health-Care Workers in Nepal: A Qualitative Study Among Frontline Health-Care Workers and Policy-Makers. Disaster Med Public Health Prep. 2021:1-9. doi: 10.1017/dmp.2021.204.

17.         Shrestha N, Gautam S, Mishra SR, Virani SS, Dhungana RR. Burden of chronic kidney disease in the general population and high-risk groups in South Asia: A systematic review and meta-analysis. PLoS One. 2021;16(10):e0258494. doi: 10.1371/journal.pone.0258494.

18.         Mehata S, Shrestha N, Ghimire S, Atkins E, Karki DK, Mishra SR. Association of altitude and urbanization with hypertension and obesity: analysis of the Nepal Demographic and Health Survey 2016. Int Health. 2021;13(2):151-60. doi: 10.1093/inthealth/ihaa034.

19.         Kazmi F, Shrestha N, Booth S, Dodwell D, Aroldi F, Foord T, et al. Next‐generation sequencing for guiding matched targeted therapies in people with relapsed or metastatic cancer. Cochrane Database of Systematic Reviews. 2021;(10). doi: 10.1002/14651858.CD014872.

20.         Gautam S, Shrestha N, Mahato S, Nguyen TPA, Mishra SR, Berg-Beckhoff G. Diabetes among tuberculosis patients and its impact on tuberculosis treatment in South Asia: a systematic review and meta-analysis. Sci Rep. 2021;11(1):2113. doi: 10.1038/s41598-021-81057-2.

21.         Dhungana RR, Pedisic Z, Pandey AR, Shrestha N, de Courten M. Barriers, Enablers and Strategies for the Treatment and Control of Hypertension in Nepal: A Systematic Review. Front Cardiovasc Med. 2021;8:716080. doi: 10.3389/fcvm.2021.716080.

22.         Dhungana RR, Pandey AR, Shrestha N. Trends in the Prevalence, Awareness, Treatment, and Control of Hypertension in Nepal between 2000 and 2025: A Systematic Review and Meta-Analysis. Int J Hypertens. 2021;2021:6610649. doi: 10.1155/2021/6610649.

23.         Shrestha N, Mishra SR, Ghimire S, Gyawali B, Pradhan PMS, Schwarz D. Application of single-level and multi-level modeling approach to examine geographic and socioeconomic variation in underweight, overweight and obesity in Nepal: findings from NDHS 2016. Sci Rep. 2020;10(1):2406. doi: 10.1038/s41598-019-56318-w.

24.         Shrestha N, Mishra SR, Ghimire S, Gyawali B, Mehata S. Burden of Diabetes and Prediabetes in Nepal: A Systematic Review and Meta-Analysis. Diabetes Ther. 2020;11(9):1935-46. doi: 10.1007/s13300-020-00884-0.

25.         Pedisic Z, Shrestha N, Kovalchik S, Stamatakis E, Liangruenrom N, Grgic J, et al. Is running associated with a lower risk of all-cause, cardiovascular and cancer mortality, and is the more the better? A systematic review and meta-analysis. Br J Sports Med. 2020;54(15):898-905. doi: 10.1136/bjsports-2018-100493.

26.         Pedisic Z, Shrestha N, Grgic J, Kovalchik S, Stamatakis E, Liangruenrom N, et al. Infographic. Is running associated with a lower risk of all-cause, cardiovascular and cancer mortality, and is more better? A systematic review and meta-analysis. Br J Sports Med. 2020;54(13):817-8. doi: 10.1136/bjsports-2019-101793.

27.         Mishra SR, Shrestha N, Gyawali B, Shrestha A. Nepal’s increasing burden of non communicable diseases and injuries, Global Burden of Disease study 1990-2017. Journal of the American College of Cardiology. 2020;75(11, Supplement 1):3478. doi: <https://doi.org/10.1016/S0735-1097(20)34105-X>.

28.         Ghimire U, Shrestha N, Gyawali B, Pradhan PMS, Mishra SR. Prevalence of American Heart Association defined ideal cardiovascular health metrics in Nepal: findings from a nationally representative cross-sectional study. Int Health. 2020;12(4):325-31. doi: 10.1093/inthealth/ihz088.

29.         Ghimire U, Shrestha N, Adhikari B, Mehata S, Pokharel Y, Mishra SR. Health system's readiness to provide cardiovascular, diabetes and chronic respiratory disease related services in Nepal: analysis using 2015 health facility survey. BMC Public Health. 2020;20(1):1163. doi: 10.1186/s12889-020-09279-z.

30.         Wieland LS, Shrestha N, Lassi ZS, Panda S, Chiaramonte D, Skoetz N. Yoga for treating urinary incontinence in women. Cochrane Database Syst Rev. 2019;2(2):CD012668. doi: 10.1002/14651858.CD012668.pub2.

31.         Shrestha N, Mehata S, Pradhan PMS, Joshi D, Mishra SR. A nationally representative study on socio-demographic and geographic correlates, and trends in tobacco use in Nepal. Sci Rep. 2019;9(1):2682. doi: 10.1038/s41598-019-39635-y.

32.         Shrestha N, Grgic J, Wiesner G, Parker A, Podnar H, Bennie JA, et al. Effectiveness of interventions for reducing non-occupational sedentary behaviour in adults and older adults: a systematic review and meta-analysis. Br J Sports Med. 2019;53(19):1206-13. doi: 10.1136/bjsports-2017-098270.

33.         Pedisic Z, Shrestha N, Loprinzi PD, Mehata S, Mishra SR. Prevalence, patterns, and correlates of physical activity in Nepal: findings from a nationally representative study using the Global Physical Activity Questionnaire (GPAQ). BMC Public Health. 2019;19(1):864. doi: 10.1186/s12889-019-7215-1.

34.         Parry SP, Coenen P, Shrestha N, O'Sullivan PB, Maher CG, Straker LM. Workplace interventions for increasing standing or walking for decreasing musculoskeletal symptoms in sedentary workers. Cochrane Database Syst Rev. 2019;2019(11). doi: 10.1002/14651858.CD012487.pub2.

35.         Mishra SR, Shrestha N, Poudyal IP, Malla M, Gyawali B, Shrestha AD, et al. May Measurement Month 2017: an analysis of blood pressure screening results in Nepal-South Asia. Eur Heart J Suppl. 2019;21(Suppl D):D83-D5. doi: 10.1093/eurheartj/suz063.

36.         Mishra SR, Ghimire S, Shrestha N, Shrestha A, Virani SS. Socio-economic inequalities in hypertension burden and cascade of services: nationwide cross-sectional study in Nepal. J Hum Hypertens. 2019;33(8):613-25. doi: 10.1038/s41371-019-0165-3.

37.         Joshi D, Shrestha S, Shrestha N. Understanding the antepartum depressive symptoms and its risk factors among the pregnant women visiting public health facilities of Nepal. PLoS One. 2019;14(4):e0214992. doi: 10.1371/journal.pone.0214992.

38.         Ghimire S, Mishra SR, Sharma A, Siweya A, Shrestha N, Adhikari B. Geographic and socio-economic variation in markers of indoor air pollution in Nepal: evidence from nationally-representative data. BMC Public Health. 2019;19(1):195. doi: 10.1186/s12889-019-6512-z. PubMed

39.         Shrestha N, Kukkonen-Harjula KT, Verbeek JH, Ijaz S, Hermans V, Pedisic Z. Workplace interventions for reducing sitting at work. Cochrane Database Syst Rev. 2018;12(12):CD010912. doi: 10.1002/14651858.CD010912.pub5.

40.         Rawal LB, Kanda K, Mahumud RA, Joshi D, Mehata S, Shrestha N, et al. Prevalence of underweight, overweight and obesity and their associated risk factors in Nepalese adults: Data from a Nationwide Survey, 2016. PLoS One. 2018;13(11):e0205912. doi: 10.1371/journal.pone.0205912.

41.         Mehata S, Shrestha N, Mehta RK, Bista B, Pandey AR, Mishra SR. Prevalence of the Metabolic Syndrome and its determinants among Nepalese adults: Findings from a nationally representative cross-sectional study. Sci Rep. 2018;8(1):14995. doi: 10.1038/s41598-018-33177-5.

42.         Mehata S, Shrestha N, Mehta R, Vaidya A, Rawal LB, Bhattarai N, et al. Prevalence, awareness, treatment and control of hypertension in Nepal: data from nationally representative population-based cross-sectional study. J Hypertens. 2018;36(8):1680-8. doi: 10.1097/HJH.0000000000001745.

43.         Grgic J, Dumuid D, Bengoechea EG, Shrestha N, Bauman A, Olds T, et al. Health outcomes associated with reallocations of time between sleep, sedentary behaviour, and physical activity: a systematic scoping review of isotemporal substitution studies. Int J Behav Nutr Phys Act. 2018;15(1):69. doi: 10.1186/s12966-018-0691-3.

44.         Wieland LS, Shrestha N, Lassi ZS, Panda S, Chiaramonte D, Skoetz N. Yoga for treatment of urinary incontinence in women. Cochrane Database Syst Rev. 2017;5(5). doi: 10.1002/14651858.CD012668.

45.         Shrestha N, Pedisic Z, Neil-Sztramko S, Kukkonen-Harjula KT, Hermans V. The Impact of Obesity in the Workplace: a Review of Contributing Factors, Consequences and Potential Solutions. Curr Obes Rep. 2016;5(3):344-60. doi: 10.1007/s13679-016-0227-6.

46.         Shrestha N, Kukkonen-Harjula KT, Verbeek JH, Ijaz S, Hermans V, Bhaumik S. Workplace interventions for reducing sitting at work. Cochrane Database Syst Rev. 2016;3(3):CD010912. doi: 10.1002/14651858.CD010912.pub3.

47.         Shrestha N, Ijaz S, Kukkonen-Harjula KT, Kumar S, Nwankwo CP. Workplace interventions for reducing sitting at work. Cochrane Database Syst Rev. 2015;1:CD010912. doi: 10.1002/14651858.CD010912.pub2.

48.         Shrestha N, Bhaumik S. Are interventions to reduce sitting at workplace effective? J Family Med Prim Care. 2015;4(3):331-2. doi: 10.4103/2249-4863.161309.

49.         Shrestha N, Ijaz S, Kukkonen‐Harjula KT, Kumar S, Nwankwo CP. Workplace interventions for reducing sitting at work. Cochrane Database of Systematic Reviews. 2014;(1). doi: 10.1002/14651858.CD010912.
